export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const FETCH_USER_BY_ID_INIT = 'FETCH_USER_BY_ID_INIT';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAILED = 'FETCH_USER_BY_ID_FAILED';

export const DELETE_USER_BY_ID_INIT = 'DELETE_USER_BY_ID';
export const DELETE_USER_BY_ID_SUCCESS = 'DELETE_USER_BY_ID_SUCCESS';
export const DELETE_USER_BY_ID_FAILED = 'DELETE_USER_BY_ID_FAILED';